spring:
  datasource:
    url: jdbc:mysql://172.19.236.69:3306/db_app_monitor?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: berry
    password: okmnji123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql

  redis:
    database: 0
    # Redis服务器地址
    host: 172.19.236.69
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: okmnji123
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    timeout: 2000ms

server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
    io-threads: 4
    worker-threads: 20


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.berry.appmonitor.core.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

# logback set path
logging:
  config: classpath:logback/logback.xml
  level:
    ROOT: INFO
    com.berry.appmonitor: DEBUG

log:
  # 运行日志存储跟路径
  path: ./logs
