server:
  port: 8088

spring:
  application:
    name: app_monitor
  profiles:
    active: dev
  mail:
    host: smtp.163.com
    port: 25
    username: berry_cooper@163.com
    password: kakaxi123
  mvc:
    favicon:
      enabled: false
  task:
    execution:
      thread-name-prefix: task-pool-
      pool:
        core-size: 4
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: scheduling-
      pool:
        size: 2
